/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaces;

import java.awt.Event;
import java.awt.GridBagLayout;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import javax.swing.InputMap;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dayanna Luna
 */
public class FRM_ControlSolicitudesMantenimiento extends javax.swing.JDialog {
    Capa_ConexionBD.Conexion conexion = new Capa_ConexionBD.Conexion();
    static Capa_Mensajes.Mensajes mensajes = new Capa_Mensajes.Mensajes();
    DefaultTableModel model;
    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
    Objetos.Control_Solicitud_Mantenimiento control_solicitud_mantenimiento = new Objetos.Control_Solicitud_Mantenimiento();
    public int estado_ColSolMant;
    
    
    public FRM_ControlSolicitudesMantenimiento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setLayout (new GridBagLayout());
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(0);
        bloquearTeclas();
        control_solicitud_mantenimiento.radio();
        rbtn_condigo_institucional.setSelected(true);
        control_solicitud_mantenimiento.activarCampos();    
        control_solicitud_mantenimiento.combo_Tipo_Area();        
        tabla_solicitudes_mantenimiento.getTableHeader().setReorderingAllowed(false);
        control_solicitud_mantenimiento.objetos_desactivados();         
        date_fecha_docSolicitud.getDateEditor().setEnabled(false);
        date_fecha_docSolicitud.setMaxSelectableDate(new java.util.Date());
        combo_idResponsable_area.removeAllItems();
    }
    
    //Bloquea acciones de copiar y pegar del teclado
    public void bloquearTeclas(){
        InputMap map1 = txt_codigoInternoInsticucional_activo.getInputMap(txt_codigoInternoInsticucional_activo.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }
    
    public void cerrar(){
      try {
         this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
          addWindowListener(new WindowAdapter (){
              public void windowClosing(WindowEvent e){
                int valor = mensajes.msg_Pregunta(null, "¿Esta seguro que desea salir?");                        
                if (valor == 0){
                    dispose();
                }                          
              }
          });
          this.setVisible(true);
      } catch (Exception e) {
          e.printStackTrace();
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        rbtn_condigo_institucional = new javax.swing.JRadioButton();
        combo_tipo_area = new javax.swing.JComboBox();
        rbtn_fecha_docSolicitud = new javax.swing.JRadioButton();
        rbtn_estado_docSolicitud = new javax.swing.JRadioButton();
        rbtn_tipo_area = new javax.swing.JRadioButton();
        combo_idResponsable_area = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        rbtn_solicitud_pendiente = new javax.swing.JRadioButton();
        rbtn_solicitud_enProceso = new javax.swing.JRadioButton();
        rbtn_solicitud_realizado = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_solicitudes_mantenimiento = new javax.swing.JTable();
        label3 = new java.awt.Label();
        date_fecha_docSolicitud = new com.toedter.calendar.JDateChooser();
        btn_buscar_solicitudes = new javax.swing.JButton();
        txt_codigoInternoInsticucional_activo = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btn_nuevo = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btn_modificarSolicitud = new javax.swing.JButton();
        btn_modificarEncargadooMantenimiento = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_enviarMantenimiento = new javax.swing.JButton();
        btn_registrarMantenimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Control de Solicitudes de Mantenimiento");
        setResizable(false);

        rbtn_condigo_institucional.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        rbtn_condigo_institucional.setText("Código Institucional");
        rbtn_condigo_institucional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtn_condigo_institucionalMouseClicked(evt);
            }
        });

        combo_tipo_area.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        combo_tipo_area.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar...", "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_tipo_area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_tipo_areaMouseClicked(evt);
            }
        });

        rbtn_fecha_docSolicitud.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        rbtn_fecha_docSolicitud.setText("Fecha de solicitud");
        rbtn_fecha_docSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtn_fecha_docSolicitudMouseClicked(evt);
            }
        });

        rbtn_estado_docSolicitud.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        rbtn_estado_docSolicitud.setText("Estado");
        rbtn_estado_docSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtn_estado_docSolicitudMouseClicked(evt);
            }
        });
        rbtn_estado_docSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_estado_docSolicitudActionPerformed(evt);
            }
        });

        rbtn_tipo_area.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        rbtn_tipo_area.setText("Tipo de Área");
        rbtn_tipo_area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtn_tipo_areaMouseClicked(evt);
            }
        });

        combo_idResponsable_area.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        combo_idResponsable_area.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar...", "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_idResponsable_area.setNextFocusableComponent(btn_buscar);
        combo_idResponsable_area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_idResponsable_areaMouseClicked(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 17))); // NOI18N

        rbtn_solicitud_pendiente.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        rbtn_solicitud_pendiente.setText("Pendiente");
        rbtn_solicitud_pendiente.setNextFocusableComponent(rbtn_solicitud_enProceso);

        rbtn_solicitud_enProceso.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        rbtn_solicitud_enProceso.setText("En Proceso");
        rbtn_solicitud_enProceso.setNextFocusableComponent(rbtn_solicitud_realizado);

        rbtn_solicitud_realizado.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        rbtn_solicitud_realizado.setText("Realizado");
        rbtn_solicitud_realizado.setNextFocusableComponent(btn_buscar);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtn_solicitud_pendiente)
                    .addComponent(rbtn_solicitud_enProceso)
                    .addComponent(rbtn_solicitud_realizado))
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtn_solicitud_pendiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtn_solicitud_enProceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtn_solicitud_realizado))
        );

        tabla_solicitudes_mantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Código Interno", "Fecha Solicitud", "Cédula Solicitante", "Solicitante", "Motivos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_solicitudes_mantenimiento.setNextFocusableComponent(btn_modificarSolicitud);
        tabla_solicitudes_mantenimiento.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla_solicitudes_mantenimiento.removeColumn(tabla_solicitudes_mantenimiento.getColumnModel().getColumn(0));
        tabla_solicitudes_mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_solicitudes_mantenimientoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_solicitudes_mantenimiento);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        label3.setText("Control de Solicitudes de Mantenimiento");

        date_fecha_docSolicitud.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        date_fecha_docSolicitud.setNextFocusableComponent(btn_buscar);
        date_fecha_docSolicitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                date_fecha_docSolicitudKeyPressed(evt);
            }
        });

        btn_buscar_solicitudes.setBorderPainted(false);
        btn_buscar_solicitudes.setContentAreaFilled(false);

        txt_codigoInternoInsticucional_activo.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_codigoInternoInsticucional_activo.setNextFocusableComponent(btn_buscar);
        txt_codigoInternoInsticucional_activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoInternoInsticucional_activoActionPerformed(evt);
            }
        });
        txt_codigoInternoInsticucional_activo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigoInternoInsticucional_activoKeyTyped(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(117, 214, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btn_nuevo.setBackground(new java.awt.Color(117, 214, 255));
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add-new-file (1).png"))); // NOI18N
        btn_nuevo.setText("   Nuevo   ");
        btn_nuevo.setFocusable(false);
        btn_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nuevo.setNextFocusableComponent(txt_codigoInternoInsticucional_activo);
        btn_nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nuevo);

        btn_imprimir.setBackground(new java.awt.Color(117, 214, 255));
        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/printer- (1).png"))); // NOI18N
        btn_imprimir.setText("   Imprimir   ");
        btn_imprimir.setFocusable(false);
        btn_imprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_imprimir.setNextFocusableComponent(btn_nuevo);
        btn_imprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_imprimir);

        btn_regresar.setBackground(new java.awt.Color(117, 214, 255));
        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logout (1).png"))); // NOI18N
        btn_regresar.setText("   Regresar");
        btn_regresar.setFocusable(false);
        btn_regresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_regresar.setName(""); // NOI18N
        btn_regresar.setNextFocusableComponent(btn_nuevo);
        btn_regresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_regresar);

        jPanel7.setBackground(new java.awt.Color(68, 69, 69));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel2.setText("RR.HH");

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_buscar(1).png"))); // NOI18N
        btn_buscar.setContentAreaFilled(false);
        btn_buscar.setNextFocusableComponent(btn_imprimir);
        btn_buscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_buscar(1).png"))); // NOI18N
        btn_buscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_buscar.png"))); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_modificarSolicitud.setBackground(new java.awt.Color(255, 255, 255));
        btn_modificarSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1/pencil.png"))); // NOI18N
        btn_modificarSolicitud.setText("Editar Solicitud");
        btn_modificarSolicitud.setContentAreaFilled(false);
        btn_modificarSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_modificarSolicitud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modificarSolicitud.setNextFocusableComponent(btn_enviarMantenimiento);
        btn_modificarSolicitud.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_modificarSolicitud.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_modificarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarSolicitudActionPerformed(evt);
            }
        });

        btn_modificarEncargadooMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/mod_persona_mant.png"))); // NOI18N
        btn_modificarEncargadooMantenimiento.setText("Encargado Mantenimiento");
        btn_modificarEncargadooMantenimiento.setToolTipText("");
        btn_modificarEncargadooMantenimiento.setContentAreaFilled(false);
        btn_modificarEncargadooMantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modificarEncargadooMantenimiento.setNextFocusableComponent(btn_registrarMantenimiento);
        btn_modificarEncargadooMantenimiento.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_modificarEncargadooMantenimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_modificarEncargadooMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarEncargadooMantenimientoActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1/rubbish-bin (1).png"))); // NOI18N
        btn_eliminar.setText("Eliminar Solicitud");
        btn_eliminar.setToolTipText("");
        btn_eliminar.setContentAreaFilled(false);
        btn_eliminar.setHideActionText(true);
        btn_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_eliminar.setNextFocusableComponent(tabla_solicitudes_mantenimiento);
        btn_eliminar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_enviarMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/servicio (2).png"))); // NOI18N
        btn_enviarMantenimiento.setText("Enviar a Mantenimiento");
        btn_enviarMantenimiento.setContentAreaFilled(false);
        btn_enviarMantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_enviarMantenimiento.setNextFocusableComponent(btn_modificarEncargadooMantenimiento);
        btn_enviarMantenimiento.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_enviarMantenimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_enviarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarMantenimientoActionPerformed(evt);
            }
        });

        btn_registrarMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1/archive.png"))); // NOI18N
        btn_registrarMantenimiento.setText("Ficha Mantenimieno");
        btn_registrarMantenimiento.setToolTipText("");
        btn_registrarMantenimiento.setContentAreaFilled(false);
        btn_registrarMantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_registrarMantenimiento.setNextFocusableComponent(btn_eliminar);
        btn_registrarMantenimiento.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_registrarMantenimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_registrarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarMantenimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_enviarMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_modificarEncargadooMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_registrarMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_modificarSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(btn_modificarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_enviarMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btn_modificarEncargadooMantenimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_registrarMantenimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar_solicitudes))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtn_condigo_institucional)
                                .addGap(18, 18, 18)
                                .addComponent(txt_codigoInternoInsticucional_activo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtn_tipo_area)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_tipo_area, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtn_fecha_docSolicitud)
                                .addGap(18, 18, 18)
                                .addComponent(date_fecha_docSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_estado_docSolicitud)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_idResponsable_area, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btn_buscar))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_buscar_solicitudes)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rbtn_fecha_docSolicitud)
                                        .addComponent(date_fecha_docSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbtn_condigo_institucional)
                                        .addComponent(txt_codigoInternoInsticucional_activo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtn_tipo_area)
                                    .addComponent(combo_tipo_area, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtn_estado_docSolicitud)
                                .addGap(18, 18, 18)
                                .addComponent(combo_idResponsable_area, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Manda los parametros para la busqueda de las solicitudes de mantenimiento
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        control_solicitud_mantenimiento.limpiarTabla(tabla_solicitudes_mantenimiento);
        control_solicitud_mantenimiento.buscarDatos_ContSolMant();
        control_solicitud_mantenimiento.desactivarBtn_contSolMant();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_modificarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarSolicitudActionPerformed
        dispose();
        FRM_RegistroSolicitudMantenimiento.save=false;
        control_solicitud_mantenimiento.mandarDatos_RegistroSolicitudMantenimiento(tabla_solicitudes_mantenimiento.getSelectedRow());
        new FRM_RegistroSolicitudMantenimiento(this, true).setVisible(true);
    }//GEN-LAST:event_btn_modificarSolicitudActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        int valor = mensajes.msg_Pregunta(this, "Esta seguro que desea eliminar ésta solicitud");
        if (valor == 0) {
            control_solicitud_mantenimiento.eliminarSolicitud_ContSolMant(tabla_solicitudes_mantenimiento.getSelectedRow());
            control_solicitud_mantenimiento.buscarDatos_ContSolMant();
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_registrarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarMantenimientoActionPerformed
        control_solicitud_mantenimiento.mandarDatos_RegMant();
        dispose();
        new FRM_RegistroMantenimiento(null, true).setVisible(true);
    }//GEN-LAST:event_btn_registrarMantenimientoActionPerformed

    private void rbtn_estado_docSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_estado_docSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_estado_docSolicitudActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        if(mensajes.msg_Pregunta(this, "¿Desea salir del cotrol de solicitudes de mantenimiento?")==0){
            dispose();
        }
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_enviarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarMantenimientoActionPerformed
        FRM_RegistroEncargadoMantenimiento.save=true;
        String valor = (String)tabla_solicitudes_mantenimiento.getValueAt(tabla_solicitudes_mantenimiento.getSelectedRow(), 0);
        FRM_RegistroEncargadoMantenimiento.id_solicitud=Integer.parseInt(valor);
        new FRM_RegistroEncargadoMantenimiento(this, true).setVisible(true);
    }//GEN-LAST:event_btn_enviarMantenimientoActionPerformed

    private void btn_modificarEncargadooMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarEncargadooMantenimientoActionPerformed
        FRM_RegistroEncargadoMantenimiento.save=false;
        String valor = (String)tabla_solicitudes_mantenimiento.getValueAt(tabla_solicitudes_mantenimiento.getSelectedRow(), 0);
        FRM_RegistroEncargadoMantenimiento.id_solicitud=Integer.parseInt(valor);
        new FRM_RegistroEncargadoMantenimiento(this, true).setVisible(true);
    }//GEN-LAST:event_btn_modificarEncargadooMantenimientoActionPerformed

    private void rbtn_condigo_institucionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtn_condigo_institucionalMouseClicked
            control_solicitud_mantenimiento.activarCampos();
            control_solicitud_mantenimiento.borrar_camposBusqueda();
    }//GEN-LAST:event_rbtn_condigo_institucionalMouseClicked

    private void rbtn_fecha_docSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtn_fecha_docSolicitudMouseClicked
        control_solicitud_mantenimiento.activarCampos();
        control_solicitud_mantenimiento.borrar_camposBusqueda();        
        
    }//GEN-LAST:event_rbtn_fecha_docSolicitudMouseClicked

    private void rbtn_tipo_areaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtn_tipo_areaMouseClicked
        control_solicitud_mantenimiento.activarCampos();
        control_solicitud_mantenimiento.borrar_camposBusqueda();
    }//GEN-LAST:event_rbtn_tipo_areaMouseClicked

    private void rbtn_estado_docSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtn_estado_docSolicitudMouseClicked
        control_solicitud_mantenimiento.activarCampos();
        rbtn_solicitud_pendiente.setSelected(true);
        control_solicitud_mantenimiento.borrar_camposBusqueda();
    }//GEN-LAST:event_rbtn_estado_docSolicitudMouseClicked

    private void tabla_solicitudes_mantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_solicitudes_mantenimientoMouseClicked
        control_solicitud_mantenimiento.verificar_estadoMantenimiento();
    }//GEN-LAST:event_tabla_solicitudes_mantenimientoMouseClicked

    private void txt_codigoInternoInsticucional_activoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoInternoInsticucional_activoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoInternoInsticucional_activoActionPerformed

    private void combo_tipo_areaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_tipo_areaMouseClicked
        
    }//GEN-LAST:event_combo_tipo_areaMouseClicked

    private void combo_idResponsable_areaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_idResponsable_areaMouseClicked
        control_solicitud_mantenimiento.combo_RecursoHumano();
    }//GEN-LAST:event_combo_idResponsable_areaMouseClicked

    private void date_fecha_docSolicitudKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date_fecha_docSolicitudKeyPressed
        char c = evt.getKeyChar();
                if(!Character.isLetter(c) && !Character.isDigit(c)){                    
                    getToolkit().beep();
                    evt.consume();
                }
    }//GEN-LAST:event_date_fecha_docSolicitudKeyPressed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        control_solicitud_mantenimiento.nuevo();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void txt_codigoInternoInsticucional_activoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoInternoInsticucional_activoKeyTyped
        char c=evt.getKeyChar(); 
        String var0 = "'";
        char var1 = '-';
        char var2 = 'ñ';
        char var3 = 'Ñ';
        if(txt_codigoInternoInsticucional_activo.getText().length()>200){
            evt.consume();
        }else{
            if (Character.isLetter(c) || Character.isDigit(c) || c==var1 && Character.toString(c).equals(var0)==false){
                if(Character.isLetter(c)){
                    evt.setKeyChar(Character.toUpperCase(c));
                }
            }else{
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_codigoInternoInsticucional_activoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_ControlSolicitudesMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_ControlSolicitudesMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_ControlSolicitudesMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_ControlSolicitudesMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRM_ControlSolicitudesMantenimiento dialog = new FRM_ControlSolicitudesMantenimiento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_buscar_solicitudes;
    public static javax.swing.JButton btn_eliminar;
    public static javax.swing.JButton btn_enviarMantenimiento;
    private javax.swing.JButton btn_imprimir;
    public static javax.swing.JButton btn_modificarEncargadooMantenimiento;
    public static javax.swing.JButton btn_modificarSolicitud;
    private javax.swing.JButton btn_nuevo;
    public static javax.swing.JButton btn_registrarMantenimiento;
    private javax.swing.JButton btn_regresar;
    public static javax.swing.JComboBox combo_idResponsable_area;
    public static javax.swing.JComboBox combo_tipo_area;
    public static com.toedter.calendar.JDateChooser date_fecha_docSolicitud;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.Label label3;
    public static javax.swing.JRadioButton rbtn_condigo_institucional;
    public static javax.swing.JRadioButton rbtn_estado_docSolicitud;
    public static javax.swing.JRadioButton rbtn_fecha_docSolicitud;
    public static javax.swing.JRadioButton rbtn_solicitud_enProceso;
    public static javax.swing.JRadioButton rbtn_solicitud_pendiente;
    public static javax.swing.JRadioButton rbtn_solicitud_realizado;
    public static javax.swing.JRadioButton rbtn_tipo_area;
    public static javax.swing.JTable tabla_solicitudes_mantenimiento;
    public static javax.swing.JTextField txt_codigoInternoInsticucional_activo;
    // End of variables declaration//GEN-END:variables
}
