/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaces;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;

import javax.swing.*;
import com.sun.pdfview.*;
import java.awt.Toolkit;

/**
 *
 * @author Erick
 */
public class JPDF extends javax.swing.JDialog {
    PagePanel panelpdf;
    JFileChooser selector;
    PDFFile pdffile;
    int indice=1;

    /**
     * Creates new form JPDF
     */
    public JPDF(java.awt.Frame parent, boolean modal, String file) {
        super(parent, modal);
        //initComponents();
        this.setTitle("MANUALES DE AYUDA ACTISOFT");
        //this.setSize(this.getToolkit().getScreenSize());
        int ancho = (int)(Toolkit.getDefaultToolkit().getScreenSize(). width); 
        int alto = (int)(Toolkit.getDefaultToolkit().getScreenSize(). height)-50; 
        this.setSize(ancho,alto);
        this.setLocationRelativeTo(null);
         panelpdf=new PagePanel();
    try{
            RandomAccessFile raf = new RandomAccessFile(file, "r");
           FileChannel channel = raf.getChannel();
           ByteBuffer buf = channel.map(FileChannel.MapMode.READ_ONLY,0, channel.size());
           pdffile = new PDFFile(buf);
           PDFPage page = pdffile.getPage(indice);
           panelpdf.showPage(page);
           repaint();
     }catch(IOException ioe){
      JOptionPane.showMessageDialog(null, "Error al abrir el archivo");
     }
  JPanel pabajo=new JPanel();
  
  JButton bsiguiente=new JButton("Siguiente");
  bsiguiente.addActionListener(new ActionListener(){
      
   @Override
   public void actionPerformed(ActionEvent e) {
    indice++;
    PDFPage page = pdffile.getPage(indice);
       panelpdf.showPage(page);
   }
  });
  
  
  
  JButton banterior=new JButton("Anterior");
  banterior.addActionListener(new ActionListener(){

   @Override
   public void actionPerformed(ActionEvent e) {
    indice--;
    PDFPage page = pdffile.getPage(indice);
       panelpdf.showPage(page);
   }
  });
  
  
  pabajo.add(banterior);
  pabajo.add(bsiguiente);
//  archivo.add(ver);
//  barra.add(archivo);
//  setJMenuBar(barra);
  add(panelpdf);
  add(pabajo,BorderLayout.SOUTH);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JPDF dialog = new JPDF(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
